### ISSUE TITLE
Error in Posix C file write function

### ISSUE THREAD

**Issue by cvandongen684** [tstih/libcpm3-z80#1]
Line 75 of libcpm3-z80-main/src/file/write.c:
            bdosret(F_WRITE, (uint16_t)&(fdblk->dma),&result);
should be:
            bdosret(F_WRITE, (uint16_t)&(fdblk->fcb),&result);
as BDOS function 21 expects the address of the FCB.

**Comment by tstih** [comment]
Thank you. It will be fixed tonight. The write functions are latest addition (written from scratch) so I guess there are more bugs hidden in there..

**Comment by tstih** [comment]
Fixed.
